Commented out the call to f_createuser since users are managed by PBIS instead of /etc/passwd

diff --git a/oracle-rdbms-server-11gR2-preinstall-verify b/oracle-rdbms-server-11gR2-preinstall-verify
--- a/oracle-rdbms-server-11gR2-preinstall-verify
+++ b/oracle-rdbms-server-11gR2-preinstall-verify
@@ -714,14 +714,14 @@ mkdir --mode 0700 -p ${TEST_LOG_LOC};
 
 mkdir --mode 0700 -p ${BACKUP_DIR};
 
-f_createuser;
-if [ $? -ne 0 ]; then
-	echo "Creating oracle user failed " >> ${PRE_PARAM_LOG}
-	echo "" >> ${PRE_PARAM_LOG}
-else
-	echo "Creating oracle user passed " >> ${PRE_PARAM_LOG}
-	echo "" >> ${PRE_PARAM_LOG}
-fi;
+#f_createuser;
+#if [ $? -ne 0 ]; then
+#	echo "Creating oracle user failed " >> ${PRE_PARAM_LOG}
+#	echo "" >> ${PRE_PARAM_LOG}
+#else
+#	echo "Creating oracle user passed " >> ${PRE_PARAM_LOG}
+#	echo "" >> ${PRE_PARAM_LOG}
+#fi;
 
 
 #This variable determines if the changes need to be effected on the system
